### ISSUE TITLE
Deprecated `react/require-extension`

### ISSUE THREAD

**Issue by juanca** [mavenlink/mavenlint#3]
See more @ https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/require-extension.md

**Comment by ahuth** [comment]
Looks like we're on an old airbnb-config. I'll update it and see what happens.

Thanks @juanca

**Comment by ahuth** [comment]
@juanca, think this thing is still an issue? Might be resolved now.

**Comment by juanca** [comment]
Should be fixed if we are using mavenlint. I had to avoid using it back in the day.
