### ISSUE TITLE
use-flux-standard-actions linter crashes when no return value

### ISSUE THREAD

**Issue by brentgaither** [mavenlink/mavenlint#35]
If an action creator uses the key word return with no value the linter blows up with 
`Module build failed: TypeError: Cannot read property 'type' of null`

**Comment by ahuth** [comment]
Interesting. Crashes and type errors are definitely not what we want.

Out of curiousity, is there a use case for action creators without return values, or does this have more to do with being in a partially-completed state?

**Comment by brentgaither** [comment]
Well I am not sure if there is a good reason and we ended up changing how we setup the action, but we were trying to return early if some condition occurred so we would not update a piece of state.

**Comment by jarednielson** [comment]
Our action creator returned a thunk and we were returning early from the thunk.

```function removeRateCardSetVersion(id) {
  return (dispatch, getState) => {
    const state = getState();
    dispatch(removeRateCardSetVersionIdFromState(id));
    dispatch(RateCardSetVersion.destroy(id));
    const activeRateCardSetVersionId = selectors.activeRateCardSetVersionId(state);
    if (activeRateCardSetVersionId.toString() !== id.toString()) {
      return; //This is the problem even though the thunk doesn't need a return value
    }
    const firstSetVersionId = selectors.rateCardSetVersions(state)[0].id;
    dispatch(updateActiveSetVersionId(firstSetVersionId));
  };
}```

**Comment by brandonduff** [comment]
Should this be a lint error? Should thunks eventually resolve to a [Flux Standard Action](https://github.com/redux-utilities/flux-standard-action)?
